- name: Criar VM Web 1
  proxmox_kvm:
    name: web1
    node: homelab
    cores: 1
    memory: 2048
    disk:
      size: 20G
      storage: local-lvm
    ostemplate: local:vztmpl/100
    network:
      - name: eth0
        bridge: vmbr0

- name: Criar VM Web 2
  proxmox_kvm:
    name: vm2
    node: homelab
    cores: 1
    memory: 2048
    disk:
      size: 20G
      storage: local-lvm
    ostemplate: local:vztmpl/100
    network:
      - name: eth0
        bridge: vmbr0

- name: Criar VM DB
  proxmox_kvm:
    name: db
    node: homelab
    cores: 1
    memory: 2048
    disk:
      size: 20G
      storage: local-lvm
    ostemplate: local:vztmpl/100
    network:
      - name: eth0
        bridge: vmbr0

- name: Instalar Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copiar arquivo de configuração
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Reiniciar Nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: Copiar arquivos do website
  copy:
    src: website/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: 0755
  become: yes
  delegate_to: "{{ item }}"
  with_items:
    - web1
    - vm2

---
- hosts: db  

  become: yes  

  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Copy MySQL configuration file (if needed)
      copy:
        src: config.cnf
        dest: /etc/mysql/config.cnf
        owner: root
        group: root
        mode: 0644

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    - name: Set MySQL root password (securely)
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"  # Provide the password via Ansible vault or environment variable
        host: localhost
        priv: "*.*:ALL"  # Grant all privileges (adjust as needed)
        state: present

    # Add more tasks for database creation, user creation, etc. as needed