- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy configuration file 
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: Copy website files
  copy:
    src: website-test/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: 0755
  become: yes
  delegate_to: "{{ item }}"
  with_items:
    - web1
    - vm2

- hosts: db  

  become: yes  

  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Copy MySQL configuration file (if needed)
      copy:
        src: config.cnf
        dest: /etc/mysql/config.cnf
        owner: root
        group: root
        mode: 0644

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    - name: Set MySQL root password (securely)
      mysql_user:
        name: root
        password: "{{ passwd_db }}"  
        host: localhost
        priv: "*.*:ALL" 
        state: present

   
